### ISSUE TITLE
Lint Target Is Broken With Latest NX

### ISSUE THREAD

**Issue by jdwillmsen** [mainawycliffe/nx-toolkits#39]
The default target for linting on latest nx 17.0.2 as of opening has changed how they call the linting executor.
Currently:
"executor": "@nx/eslint:eslint",
Does not work but making slight altercation:
Works:
"executor": "@nx/eslint:lint",

**Comment by mainawycliffe** [comment]
@jdwillmsen thanks for the bug report and suggestion for a work around, let migrate nx and fix the issue.

**Comment by mainawycliffe** [comment]
This is fixed
